name: flutter_base_v2
description: A new Flutter project.
publish_to: 'none'

version: 1.0.15+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dart_json_mapper: ^2.2.9
  flutter_native_splash: ^2.3.1
  get: ^4.6.5
  get_storage: ^2.1.1
  flutter_secure_storage: ^9.2.2
  url_launcher: ^6.1.12
  functional_widget_annotation: ^0.10.0
  flutter_form_builder: ^9.1.0
  dio: ^5.3.2
  form_builder_validators: ^11.0.0
  jiffy: ^6.3.1
  logger: ^2.0.1
  retrofit: ^4.0.1
  adaptive_dialog: ^2.2.1+2
  hive: ^2.2.3
  envied: ^0.5.4+1
  package_info_plus: ^8.1.0
  infinite_scroll_pagination: ^4.0.0
  hive_flutter: ^1.1.0
  google_sign_in: ^6.1.4
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  sign_in_with_apple: ^6.1.3
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^18.0.0
  permission_handler: ^11.3.1
  flutter_slidable: ^3.0.0
  persistent_bottom_nav_bar: ^6.2.1
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  intl: any
  json_annotation: ^4.9.0
  image_picker: ^1.1.2
  qr_flutter: ^4.1.0
  http_parser: ^4.0.2
  photo_gallery: ^2.2.1
  scan: ^1.6.0
  notification_center: ^1.0.2
  qr_code_scanner: ^1.0.1
  device_info_plus: ^11.1.1
  webview_flutter: ^4.10.0
  persistent_bottom_nav_bar_v2: ^5.3.1
  flutter_animate: ^4.5.2
  animations: ^2.0.11
  animate_do: ^3.3.4
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.1
  functional_widget: ^0.10.1
  retrofit_generator: ^9.1.3
  envied_generator: ^0.5.4+1
  hive_generator: ^2.0.0
  intl_utils: ^2.5.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SFProDisplay-Thin.ttf
          weight: 100
        - asset: assets/fonts/SFProDisplay-Ultralight.ttf
          weight: 200
        - asset: assets/fonts/SFProDisplay-Light.ttf
          weight: 300
        - asset: assets/fonts/SFProDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/SFProDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/SFProDisplay-Semibold.ttf
          weight: 600
        - asset: assets/fonts/SFProDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/SFProDisplay-Black.ttf
          weight: 800
        - asset: assets/fonts/SFProDisplay-Heavy.ttf
          weight: 900

flutter_gen:
  integrations:
    flutter_svg: true
  output: lib/utils/gen

  colors:
    inputs:
      - assets/colors/colors.xml

flutter_intl:
  enabled: true
  arb-dir: lib/l10n
  template-arb-file: intl_en.arb
  output-dir: lib/generated